swagger: "2.0"
info:
  title: "Tesla Management API"
  description: "API for the Tesla Management application"
  version: "1.0.0"

schemes:
  - "https"
produces:
  - "application/json"

paths:
  "/{proxy}":
    parameters:
      - name: "proxy"
        in: "path"
        required: true
        type: "string"
    get:
      summary: "Proxy GET requests"
      operationId: "proxyGet"
      x-google-backend:
        address: https://tesla-management-service-71286392534.us-central1.run.app
      security:
        - api_key: []
      responses:
        "200":
          description: "A successful response"
    post:
      summary: "Proxy POST requests"
      operationId: "proxyPost"
      x-google-backend:
        address: https://tesla-management-service-71286392534.us-central1.run.app
      security:
        - api_key: []
      responses:
        "200":
          description: "A successful response"
    put:
      summary: "Proxy PUT requests"
      operationId: "proxyPut"
      x-google-backend:
        address: https://tesla-management-service-71286392534.us-central1.run.app
      security:
        - api_key: []
      responses:
        "200":
          description: "A successful response"
    delete:
      summary: "Proxy DELETE requests"
      operationId: "proxyDelete"
      x-google-backend:
        address: https://tesla-management-service-71286392534.us-central1.run.app
      security:
        - api_key: []
      responses:
        "200":
          description: "A successful response"

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"