alter table if exists accounts add constraint FKlsy3ac8vc53y9u2we16xbev23 foreign key (received_by) references user_detail;
alter table if exists accounts add column expense_amount numeric(38,2);
alter table if exists accounts add column expense_type varchar(255);
alter table if exists accounts add column invalid_transaction boolean;
alter table if exists accounts add constraint FKlsy3ac8vc53y9u2we16xbev23 foreign key (received_by) references user_detail;
alter table if exists accounts add constraint FKlsy3ac8vc53y9u2we16xbev23 foreign key (received_by) references user_detail;
alter table if exists accounts add column created_at timestamp(6) not null;
alter table if exists accounts add column is_delete boolean not null;
alter table if exists accounts add column updated_at timestamp(6) not null;
alter table if exists accounts add column transaction_id bigint;
alter table if exists staff add column is_salary_paid boolean not null;
alter table if exists student add column is_fees_paid boolean;
create table transactions (transaction_id bigint not null, amount numeric(38,2) not null, category varchar(255) not null, comments varchar(255), created_at timestamp(6) not null, is_invalid boolean not null, payment_mode varchar(255) not null, date timestamp(6) not null, transaction_type varchar(255) not null, updated_at timestamp(6) not null, branch_id bigint, received_by bigint, staff_id bigint, student_id bigint, primary key (transaction_id));
create sequence transactions_seq start with 1 increment by 50;
alter table if exists accounts add constraint FKij6okg1qcxqhd4jy7wcu2awup foreign key (transaction_id) references transactions;
alter table if exists transactions add constraint FKti961feu1yn980b0kebj16cxh foreign key (branch_id) references branches;
alter table if exists transactions add constraint FK15k7r8ev1bpkrbslfrbp7q32t foreign key (received_by) references user_detail;
alter table if exists transactions add constraint FKfner4cly0tqxmdut6udfxcb2b foreign key (staff_id) references staff;
alter table if exists transactions add constraint FK8klpun9u3aoqpyaaxjk36j1bd foreign key (student_id) references student;
alter table if exists staff add column is_salary_paid boolean not null;
create table accounts (account_id bigint not null, comments varchar(255), created_at timestamp(6) not null, date timestamp(6) not null, is_delete boolean not null, updated_at timestamp(6) not null, received_by bigint, transaction_id bigint, primary key (account_id));
alter table if exists accounts add constraint FKlsy3ac8vc53y9u2we16xbev23 foreign key (received_by) references user_detail;
alter table if exists accounts add constraint FKij6okg1qcxqhd4jy7wcu2awup foreign key (transaction_id) references transactions;
create table accounts (account_id bigint not null, comments varchar(255), created_at timestamp(6) not null, date timestamp(6) not null, is_delete boolean not null, updated_at timestamp(6) not null, received_by bigint, transaction_id bigint, primary key (account_id));
alter table if exists accounts drop constraint if exists UK_jdncyo1sl92qj7ldiedh33xte;
alter table if exists accounts add constraint UK_jdncyo1sl92qj7ldiedh33xte unique (transaction_id);
alter table if exists accounts add constraint FKlsy3ac8vc53y9u2we16xbev23 foreign key (received_by) references user_detail;
alter table if exists accounts add constraint FKij6okg1qcxqhd4jy7wcu2awup foreign key (transaction_id) references transactions;
alter table if exists transactions add column transaction_made_by bigint;
alter table if exists transactions add constraint FKo7r6iva6ty7xviol1cpvlmuah foreign key (transaction_made_by) references user_detail;
create table accounts (account_id bigint not null, comments varchar(255), created_at timestamp(6) not null, date timestamp(6) not null, is_delete boolean not null, updated_at timestamp(6) not null, received_by bigint, transaction_id bigint, primary key (account_id));
create table transactions (transaction_id bigint not null, amount numeric(38,2) not null, category varchar(255) not null, comments varchar(255), created_at timestamp(6) not null, is_invalid boolean not null, payment_mode varchar(255) not null, date timestamp(6) not null, transaction_type varchar(255) not null, updated_at timestamp(6) not null, branch_id bigint, staff_id bigint, student_id bigint, transaction_made_by bigint, primary key (transaction_id));
alter table if exists accounts drop constraint if exists UK_jdncyo1sl92qj7ldiedh33xte;
alter table if exists accounts add constraint UK_jdncyo1sl92qj7ldiedh33xte unique (transaction_id);
alter table if exists accounts add constraint FKlsy3ac8vc53y9u2we16xbev23 foreign key (received_by) references user_detail;
alter table if exists accounts add constraint FKij6okg1qcxqhd4jy7wcu2awup foreign key (transaction_id) references transactions;
alter table if exists transactions add constraint FKti961feu1yn980b0kebj16cxh foreign key (branch_id) references branches;
alter table if exists transactions add constraint FKfner4cly0tqxmdut6udfxcb2b foreign key (staff_id) references staff;
alter table if exists transactions add constraint FK8klpun9u3aoqpyaaxjk36j1bd foreign key (student_id) references student;
alter table if exists transactions add constraint FKo7r6iva6ty7xviol1cpvlmuah foreign key (transaction_made_by) references user_detail;
alter table if exists accounts add column transaction_made_by bigint;
alter table if exists accounts add constraint FK9d8ahaf7on6h38vvk4qpkynd5 foreign key (transaction_made_by) references user_detail;
alter table if exists transactions add column is_delete boolean not null;
alter table if exists transactions add column is_delete boolean not null;
alter table if exists transactions add column is_delete BOOLEAN DEFAULT FALSE not null;
create table allocation_requests (request_id bigserial not null, comments varchar(255), created_at timestamp(6) not null, entity_id bigint not null, entity_type varchar(255) not null check (entity_type in ('Student','Faculty')), request_status varchar(255) not null check (request_status in ('Pending','Approved','Rejected')), request_type varchar(255) not null check (request_type in ('Allocation','Deallocation')), updated_at timestamp(6) not null, approved_by bigint, branch_id bigint not null, requested_by bigint not null, primary key (request_id));
alter table if exists branches add column created_at timestamp(6) not null;
alter table if exists branches add column updated_at timestamp(6) not null;
create table class_sessions (class_session_id bigserial not null, created_at timestamp(6) not null, session_date date not null, updated_at timestamp(6) not null, class_id bigint not null, staff_id bigint not null, primary key (class_session_id));
alter table if exists classes add column created_at timestamp(6) not null;
alter table if exists classes add column updated_at timestamp(6) not null;
create table enrollments (enrollment_id bigserial not null, created_at timestamp(6) not null, enrollment_date date not null, updated_at timestamp(6) not null, class_id bigint not null, student_id bigint not null, primary key (enrollment_id));
alter table if exists hqtable add column created_at timestamp(6) not null;
alter table if exists hqtable add column updated_at timestamp(6) not null;
create table payment_modes (mode_id bigserial not null, created_at timestamp(6) not null, mode_name varchar(255) not null, updated_at timestamp(6) not null, primary key (mode_id));
alter table if exists roles add column created_at timestamp(6) not null;
alter table if exists roles add column role_name varchar(255) not null;
alter table if exists roles add column updated_at timestamp(6) not null;
alter table if exists staff add column created_at timestamp(6) not null;
alter table if exists staff add column updated_at timestamp(6) not null;
alter table if exists staff alter column branch_id set data type bigint;
alter table if exists staff add column user_id bigint;
alter table if exists student_attendance add column attendance_id bigserial not null;
alter table if exists student_attendance add column created_at timestamp(6) not null;
alter table if exists student_attendance add column updated_at timestamp(6) not null;
alter table if exists student_attendance add column class_session_id bigint not null;
create table students (student_id bigserial not null, batch_year integer, board_of_school varchar(255), created_at timestamp(6) not null, dob date, gender varchar(10), is_active BOOLEAN DEFAULT TRUE not null, is_approved BOOLEAN DEFAULT FALSE not null, is_fees_paid boolean not null, parent_contact varchar(255), parent_name varchar(255), reason_for_deactivation varchar(255), school_name varchar(255), school_std varchar(50), student_address varchar(255), student_name varchar(255) not null, updated_at timestamp(6) not null, branch_id bigint not null, created_by bigint, primary key (student_id));
create table transaction_categories (category_id bigserial not null, category_name varchar(255) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, primary key (category_id));
create table transaction_types (type_id bigserial not null, type_name varchar(255) not null, primary key (type_id));
alter table if exists transactions alter column amount set data type numeric(15,2);
alter table if exists transactions add column is_deleted BOOLEAN DEFAULT FALSE not null;
alter table if exists transactions add column category_id bigint not null;
alter table if exists transactions add column payment_mode_id bigint not null;
alter table if exists transactions add column transaction_type_id bigint not null;
create table user_roles (user_role_id bigserial not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, branch_id bigint, role_id bigint not null, user_id bigint not null, primary key (user_role_id));
create table users (user_id bigserial not null, created_at timestamp(6) not null, is_active BOOLEAN DEFAULT TRUE not null, modified_at timestamp(6) not null, password varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table if exists class_sessions drop constraint if exists unique_class_session;
alter table if exists class_sessions add constraint unique_class_session unique (class_id, session_date);
alter table if exists enrollments drop constraint if exists unique_student_class;
alter table if exists enrollments add constraint unique_student_class unique (student_id, class_id);
alter table if exists payment_modes drop constraint if exists UK_gjw1p1k54fwgnfm1ygb5pkd5s;
alter table if exists payment_modes add constraint UK_gjw1p1k54fwgnfm1ygb5pkd5s unique (mode_name);
alter table if exists roles drop constraint if exists UK_716hgxp60ym1lifrdgp67xt5k;
alter table if exists roles add constraint UK_716hgxp60ym1lifrdgp67xt5k unique (role_name);
alter table if exists staff drop constraint if exists UK_7qatq4kob2sr6rlp44khhj53g;
alter table if exists staff add constraint UK_7qatq4kob2sr6rlp44khhj53g unique (user_id);
alter table if exists student_attendance drop constraint if exists unique_attendance;
alter table if exists student_attendance add constraint unique_attendance unique (class_session_id, student_id);
alter table if exists transaction_categories drop constraint if exists UK_5052cbkroieqo2x5kjg9qjo6a;
alter table if exists transaction_categories add constraint UK_5052cbkroieqo2x5kjg9qjo6a unique (category_name);
alter table if exists transaction_types drop constraint if exists UK_e9ew1oh6kxv9dyoxn21kce37r;
alter table if exists transaction_types add constraint UK_e9ew1oh6kxv9dyoxn21kce37r unique (type_name);
alter table if exists user_roles drop constraint if exists unique_user_role_branch;
alter table if exists user_roles add constraint unique_user_role_branch unique (user_id, role_id, branch_id);
alter table if exists users drop constraint if exists UK_r43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists allocation_requests add constraint FKaev175caubonh5tkgx3ecs6dq foreign key (approved_by) references users;
alter table if exists allocation_requests add constraint FKmewdbs4qmmli7kh2pijfi7q0n foreign key (branch_id) references branches;
alter table if exists allocation_requests add constraint FK7bx3p1usnybfk0x7idnweubgj foreign key (requested_by) references users;
alter table if exists branches add constraint FK1sriyb6bw6m3knij8svsjx9hj foreign key (hq_id) references hqtable;
alter table if exists class_sessions add constraint FK1w2pxpii8b2dhn7pcylfpiygh foreign key (class_id) references classes;
alter table if exists class_sessions add constraint FKsud0wfajqdlf3sng8hbskwhbk foreign key (staff_id) references staff;
alter table if exists classes add constraint FKtfq7dj1h7fbsrshdle005d5h5 foreign key (branch_id) references branches;
alter table if exists classes add constraint FK598kjxsn1wqp4xxehg4tiiff4 foreign key (staff_id) references staff;
alter table if exists enrollments add constraint FKloh1q3o1ua6yuw9mwqdvhc54u foreign key (class_id) references classes;
alter table if exists enrollments add constraint FK8kf1u1857xgo56xbfmnif2c51 foreign key (student_id) references students;
alter table if exists staff add constraint FK1lha0ag3td43wl4slo0mnujdq foreign key (branch_id) references branches;
alter table if exists staff add constraint FKdlvw23ak3u9v9bomm8g12rtc0 foreign key (user_id) references users;
alter table if exists student_attendance add constraint FKnnhikyk7n9kdbdti33vi379vq foreign key (class_session_id) references class_sessions;
alter table if exists student_attendance add constraint FKom8v4b1hh9n50u1fpx4xvw3oq foreign key (student_id) references students;
alter table if exists students add constraint FKn1fivp3d0vw7p2hvxm698lqgc foreign key (branch_id) references branches;
alter table if exists students add constraint FKqhlekr2jpkjp6dgfj8kv266a5 foreign key (created_by) references users;
alter table if exists transactions add constraint FK9brs0oqbnaadq0txp55ny3p0j foreign key (category_id) references transaction_categories;
alter table if exists transactions add constraint FKj0svw7gk5bunfc20519248yod foreign key (payment_mode_id) references payment_modes;
alter table if exists transactions add constraint FK79fflsn23798fyh9hp8h66xkn foreign key (student_id) references students;
alter table if exists transactions add constraint FKctdtdhixc9kt3jkq2qjetp45g foreign key (transaction_made_by) references users;
alter table if exists transactions add constraint FKohg1hygc86j35hf0ndlaxc3qy foreign key (transaction_type_id) references transaction_types;
alter table if exists user_roles add constraint FKn71s1ys1nx94y9o03rk7lvea6 foreign key (branch_id) references branches;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists branches add column created_at timestamp(6) not null;
alter table if exists branches add column updated_at timestamp(6) not null;
alter table if exists class_sessions add column created_at timestamp(6) not null;
alter table if exists class_sessions add column updated_at timestamp(6) not null;
alter table if exists classes add column created_at timestamp(6) not null;
alter table if exists classes add column updated_at timestamp(6) not null;
alter table if exists enrollments add column created_at timestamp(6) not null;
alter table if exists enrollments add column updated_at timestamp(6) not null;
create table hqtable (hq_id bigserial not null, address varchar(255) not null, created_at timestamp(6) not null, hq_name varchar(255) not null, updated_at timestamp(6) not null, primary key (hq_id));
alter table if exists payment_modes add column created_at timestamp(6) not null;
alter table if exists payment_modes add column updated_at timestamp(6) not null;
alter table if exists roles add column created_at timestamp(6) not null;
alter table if exists roles add column updated_at timestamp(6) not null;
alter table if exists staff add column created_at timestamp(6) not null;
alter table if exists staff add column updated_at timestamp(6) not null;
alter table if exists student_attendance add column created_at timestamp(6) not null;
alter table if exists student_attendance add column updated_at timestamp(6) not null;
alter table if exists transaction_categories add column created_at timestamp(6) not null;
alter table if exists transaction_categories add column updated_at timestamp(6) not null;
alter table if exists user_roles add column created_at timestamp(6) not null;
alter table if exists user_roles add column updated_at timestamp(6) not null;
alter table if exists branches add constraint FK1sriyb6bw6m3knij8svsjx9hj foreign key (hq_id) references hqtable;
alter table if exists roles add column created_at timestamp(6) not null;
alter table if exists roles add column updated_at timestamp(6) not null;
alter table if exists roles add column created_at timestamp(6) not null;
alter table if exists roles add column updated_at timestamp(6) not null;
alter table if exists roles add column created_at timestamp(6) not null;
alter table if exists roles add column updated_at timestamp(6) not null;
alter table if exists roles add column created_at timestamp(6) not null;
alter table if exists roles add column updated_at timestamp(6) not null;
alter table if exists roles add column created_at timestamp(6) not null;
alter table if exists roles add column updated_at timestamp(6) not null;
create table allocation_requests (request_id bigserial not null, comments varchar(255), created_at timestamp(6) not null, entity_id bigint not null, entity_type varchar(255) not null check (entity_type in ('Student','Faculty')), request_status varchar(255) not null check (request_status in ('Pending','Approved','Rejected')), request_type varchar(255) not null check (request_type in ('Allocation','Deallocation')), updated_at timestamp(6) not null, approved_by bigint, branch_id bigint not null, requested_by bigint not null, primary key (request_id));
create table branches (branch_id bigserial not null, branch_address varchar(255) not null, branch_name varchar(255) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, hq_id bigint not null, primary key (branch_id));
create table class_sessions (class_session_id bigserial not null, created_at timestamp(6) not null, session_date date not null, updated_at timestamp(6) not null, class_id bigint not null, staff_id bigint not null, primary key (class_session_id));
create table classes (class_id bigserial not null, batch_name varchar(255) not null, batch_timings varchar(255) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, branch_id bigint not null, staff_id bigint not null, primary key (class_id));
create table enrollments (enrollment_id bigserial not null, created_at timestamp(6) not null, enrollment_date date not null, updated_at timestamp(6) not null, class_id bigint not null, student_id bigint not null, primary key (enrollment_id));
create table hqtable (hq_id bigserial not null, address varchar(255) not null, created_at timestamp(6) not null, hq_name varchar(255) not null, updated_at timestamp(6) not null, primary key (hq_id));
create table payment_modes (mode_id bigserial not null, created_at timestamp(6) not null, mode_name varchar(255) not null, updated_at timestamp(6) not null, primary key (mode_id));
create table roles (role_id bigserial not null, created_at timestamp(6) not null, role_name varchar(255) not null, updated_at timestamp(6) not null, primary key (role_id));
create table staff (staff_id bigserial not null, address varchar(255), contact_number varchar(255), created_at timestamp(6) not null, is_active BOOLEAN DEFAULT TRUE not null, is_salary_paid BOOLEAN DEFAULT FALSE not null, is_teaching_staff boolean not null, reason_for_deactivation varchar(255), staff_name varchar(255) not null, updated_at timestamp(6) not null, branch_id bigint not null, user_id bigint, primary key (staff_id));
create table student_attendance (attendance_id bigserial not null, created_at timestamp(6) not null, is_present boolean not null, updated_at timestamp(6) not null, class_session_id bigint not null, student_id bigint not null, primary key (attendance_id));
create table students (student_id bigserial not null, batch_year integer, board_of_school varchar(255), created_at timestamp(6) not null, dob date, gender varchar(10), is_active BOOLEAN DEFAULT TRUE not null, is_approved BOOLEAN DEFAULT FALSE not null, is_fees_paid boolean not null, parent_contact varchar(255), parent_name varchar(255), reason_for_deactivation varchar(255), school_name varchar(255), school_std varchar(50), student_address varchar(255), student_name varchar(255) not null, updated_at timestamp(6) not null, branch_id bigint not null, created_by bigint, primary key (student_id));
create table transaction_categories (category_id bigserial not null, category_name varchar(255) not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, primary key (category_id));
create table transaction_types (type_id bigserial not null, type_name varchar(255) not null, primary key (type_id));
create table transactions (transaction_id bigserial not null, amount numeric(15,2) not null, comments varchar(255), created_at timestamp(6) not null, date timestamp(6) not null, is_deleted BOOLEAN DEFAULT FALSE not null, is_invalid BOOLEAN DEFAULT FALSE not null, updated_at timestamp(6) not null, branch_id bigint not null, category_id bigint not null, payment_mode_id bigint not null, staff_id bigint, student_id bigint, transaction_made_by bigint not null, transaction_type_id bigint not null, primary key (transaction_id));
create table user_roles (user_role_id bigserial not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, branch_id bigint, role_id bigint not null, user_id bigint not null, primary key (user_role_id));
create table users (user_id bigserial not null, created_at timestamp(6) not null, is_active BOOLEAN DEFAULT TRUE not null, modified_at timestamp(6) not null, password varchar(255) not null, username varchar(255) not null, primary key (user_id));
alter table if exists class_sessions drop constraint if exists unique_class_session;
alter table if exists class_sessions add constraint unique_class_session unique (class_id, session_date);
alter table if exists enrollments drop constraint if exists unique_student_class;
alter table if exists enrollments add constraint unique_student_class unique (student_id, class_id);
alter table if exists payment_modes drop constraint if exists UK_gjw1p1k54fwgnfm1ygb5pkd5s;
alter table if exists payment_modes add constraint UK_gjw1p1k54fwgnfm1ygb5pkd5s unique (mode_name);
alter table if exists roles drop constraint if exists UK_716hgxp60ym1lifrdgp67xt5k;
alter table if exists roles add constraint UK_716hgxp60ym1lifrdgp67xt5k unique (role_name);
alter table if exists staff drop constraint if exists UK_7qatq4kob2sr6rlp44khhj53g;
alter table if exists staff add constraint UK_7qatq4kob2sr6rlp44khhj53g unique (user_id);
alter table if exists student_attendance drop constraint if exists unique_attendance;
alter table if exists student_attendance add constraint unique_attendance unique (class_session_id, student_id);
alter table if exists transaction_categories drop constraint if exists UK_5052cbkroieqo2x5kjg9qjo6a;
alter table if exists transaction_categories add constraint UK_5052cbkroieqo2x5kjg9qjo6a unique (category_name);
alter table if exists transaction_types drop constraint if exists UK_e9ew1oh6kxv9dyoxn21kce37r;
alter table if exists transaction_types add constraint UK_e9ew1oh6kxv9dyoxn21kce37r unique (type_name);
alter table if exists user_roles drop constraint if exists unique_user_role_branch;
alter table if exists user_roles add constraint unique_user_role_branch unique (user_id, role_id, branch_id);
alter table if exists users drop constraint if exists UK_r43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists allocation_requests add constraint FKaev175caubonh5tkgx3ecs6dq foreign key (approved_by) references users;
alter table if exists allocation_requests add constraint FKmewdbs4qmmli7kh2pijfi7q0n foreign key (branch_id) references branches;
alter table if exists allocation_requests add constraint FK7bx3p1usnybfk0x7idnweubgj foreign key (requested_by) references users;
alter table if exists branches add constraint FK1sriyb6bw6m3knij8svsjx9hj foreign key (hq_id) references hqtable;
alter table if exists class_sessions add constraint FK1w2pxpii8b2dhn7pcylfpiygh foreign key (class_id) references classes;
alter table if exists class_sessions add constraint FKsud0wfajqdlf3sng8hbskwhbk foreign key (staff_id) references staff;
alter table if exists classes add constraint FKtfq7dj1h7fbsrshdle005d5h5 foreign key (branch_id) references branches;
alter table if exists classes add constraint FK598kjxsn1wqp4xxehg4tiiff4 foreign key (staff_id) references staff;
alter table if exists enrollments add constraint FKloh1q3o1ua6yuw9mwqdvhc54u foreign key (class_id) references classes;
alter table if exists enrollments add constraint FK8kf1u1857xgo56xbfmnif2c51 foreign key (student_id) references students;
alter table if exists staff add constraint FK1lha0ag3td43wl4slo0mnujdq foreign key (branch_id) references branches;
alter table if exists staff add constraint FKdlvw23ak3u9v9bomm8g12rtc0 foreign key (user_id) references users;
alter table if exists student_attendance add constraint FKnnhikyk7n9kdbdti33vi379vq foreign key (class_session_id) references class_sessions;
alter table if exists student_attendance add constraint FKom8v4b1hh9n50u1fpx4xvw3oq foreign key (student_id) references students;
alter table if exists students add constraint FKn1fivp3d0vw7p2hvxm698lqgc foreign key (branch_id) references branches;
alter table if exists students add constraint FKqhlekr2jpkjp6dgfj8kv266a5 foreign key (created_by) references users;
alter table if exists transactions add constraint FKti961feu1yn980b0kebj16cxh foreign key (branch_id) references branches;
alter table if exists transactions add constraint FK9brs0oqbnaadq0txp55ny3p0j foreign key (category_id) references transaction_categories;
alter table if exists transactions add constraint FKj0svw7gk5bunfc20519248yod foreign key (payment_mode_id) references payment_modes;
alter table if exists transactions add constraint FKfner4cly0tqxmdut6udfxcb2b foreign key (staff_id) references staff;
alter table if exists transactions add constraint FK79fflsn23798fyh9hp8h66xkn foreign key (student_id) references students;
alter table if exists transactions add constraint FKctdtdhixc9kt3jkq2qjetp45g foreign key (transaction_made_by) references users;
alter table if exists transactions add constraint FKohg1hygc86j35hf0ndlaxc3qy foreign key (transaction_type_id) references transaction_types;
alter table if exists user_roles add constraint FKn71s1ys1nx94y9o03rk7lvea6 foreign key (branch_id) references branches;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
create table refresh_tokens (id serial not null, expiry_date timestamp(6) with time zone, token varchar(255), user_id bigint, primary key (id));
alter table if exists refresh_tokens drop constraint if exists UK_7tdcd6ab5wsgoudnvj7xf1b7l;
alter table if exists refresh_tokens add constraint UK_7tdcd6ab5wsgoudnvj7xf1b7l unique (user_id);
alter table if exists refresh_tokens add constraint FK1lih5y2npsf8u5o3vhdb9y0os foreign key (user_id) references users;
