# Development Database Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:postgresql://localhost:5432/tesla_management_v4
spring.datasource.username=postgres
spring.datasource.password=2456
#spring.cloud.gcp.sql.instance-connection-name=euphoric-quanta-460903-c9:us-central1:tesla-postgres-db
#spring.cloud.gcp.sql.database-name=postgres
#spring.datasource.url=jdbc:postgresql:///postgres?cloudSqlInstance=euphoric-quanta-460903-c9:us-central1:tesla-postgres-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=2456
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.cloud.gcp.sql.enabled=true
#spring.cloud.gcp.secretmanager.enabled=true


# Development JWT Configuration
jwt.secret=357638792F423F4428472B4B6250655368566D597133743677397A2443264629
jwt.access-token.expiry=3000000
refresh-token.expiry=30000000

# Development Logging
logging.level.com.example.TeslaManagement=DEBUG
logging.level.org.springframework.security=DEBUG