# Production Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Production JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access-token.expiry=3000000
refresh-token.expiry=600000

# Production Logging
logging.level.com.example.TeslaManagement=INFO
logging.level.org.springframework.security=INFO