spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tesla_management
    username: spydaa_admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect