# Development Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tesla_management_v2
spring.datasource.username=postgres
spring.datasource.password=2456

# Development JWT Configuration
jwt.secret=357638792F423F4428472B4B6250655368566D597133743677397A2443264629
jwt.access-token.expiry=3000000
refresh-token.expiry=600000

# Development Logging
logging.level.com.example.TeslaManagement=DEBUG
logging.level.org.springframework.security=DEBUG