spring.datasource.url=jdbc:postgresql://localhost:5432/tesla_management
spring.datasource.username=postgres
spring.datasource.password=2456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.properties.jakarta.persistence.validation.mode=none
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=update
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=update
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=update.sql

jwt.token.validity=18000
jwt.signing.key=YourSignInKey
jwt.authorities.key=roles
jwt.token.prefix=Bearer
jwt.header.string=Authorization